# Form implementation generated from reading ui file 'bank1.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from gui2 import Ui_MainWindow as Bank2Window
from bank import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 403)
        MainWindow.setMinimumSize(QtCore.QSize(450, 400))
        MainWindow.setMaximumSize(QtCore.QSize(450, 1000))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 90, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 260, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 40, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(50, 210, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(260, 210, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 140, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Bank"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.radioButton.setText(_translate("MainWindow", "Checking Account"))
        self.radioButton_2.setText(_translate("MainWindow", "Saving Account"))
        self.label_3.setText(_translate("MainWindow", "Password"))

class Bank1App(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.bank = Bank()
        self.account = None

        self.ui.pushButton.clicked.connect(self.open_bank2)

    def open_bank2(self):
        name = self.ui.lineEdit.text().strip()
        password = self.ui.lineEdit_2.text().strip()

        if not name or not password:
            QtWidgets.QMessageBox.warning(self, "Error", "Please enter both name and password!")
            return

        if self.ui.radioButton.isChecked():
            account_type = "Checking"
        elif self.ui.radioButton_2.isChecked():
            account_type = "Saving"
        else:
            QtWidgets.QMessageBox.warning(self, "Error", "Please select an account type!")
            return

        account_result = self.bank.information(name, password, account_type)

        if account_result[0] is None:
            QtWidgets.QMessageBox.warning(self, "Error", "Incorrect password!")
            return

        self.account, is_new = account_result

        if is_new:
            QtWidgets.QMessageBox.information(self, "Info", "New account created.")

        self.bank2_window = QtWidgets.QMainWindow()
        self.bank2_ui = Bank2Window()
        self.bank2_ui.setupUi(self.bank2_window)

        self.bank2_ui.label_3.setText(
            f"Name: {self.account.get_name()}, Balance: ${self.account.get_balance():.2f}")

        self.bank2_ui.pushButton.clicked.connect(self.handle_transaction)

        self.ui.lineEdit_2.clear()

        self.bank2_window.show()

    def handle_transaction(self):
        try:
            amount = float(self.bank2_ui.lineEdit_2.text())

            if self.bank2_ui.radioButton.isChecked():
                if not self.account.deposit(amount):
                    QtWidgets.QMessageBox.warning(self, "Error", "Deposit failed.")
            elif self.bank2_ui.radioButton_2.isChecked():
                if not self.account.withdraw(amount):
                    QtWidgets.QMessageBox.warning(self, "Error", "Withdraw failed.")
            else:
                QtWidgets.QMessageBox.warning(self, "Error", "Please select a transaction type.")

            self.bank2_ui.label.setText(
                f"Name: {self.account.get_name()}, Balance: ${self.account.get_balance():.2f}")


        except ValueError:
            QtWidgets.QMessageBox.warning(self, "Invalid Input", "Please enter a valid number.")

